In [156]:
import csv

def main():
    f = open('Seoul_Temp.csv','r',encoding='cp949')
    data = csv.reader(f)
    header = next(data)
    #print(header)
    max_temp = 0
    low_temp =0
    avr_temp = 0
    avr_low = 0
    avr_max =0
    count = 0

    for row in data:
        if(row[-1]==''):
            row[-1] = 0
        row[-1] = float(row[-1])
        if max_temp < row[-1]:
            max_date = row[0]
            max_temp = row[-1]
        
        if(row[-2]==''):
            row[-2] = 0
        row[-2] = float(row[-2])
        if low_temp > row[-2]:
            low_date = row[0]
            low_temp = row[-2]
            
        #연평균 기온
        count = count+1
        if(row[2]==''):
            row[2] = 0
        row[2] = float(row[2])
        avr_temp = row[2]+avr_temp
        
        #연평균 최저 기온
        if(row[-2]==''):
            row[-2]=0
        row[-2] = float(row[-2])
        avr_low = row[-2]+avr_low
        
        #연평균 최고 기온
        if(row[-1]==''):
            row[-1]=0
        row[-1] = float(row[-1])
        avr_max = row[-1]+avr_max


    avr_temp = avr_temp/count
    avr_low = avr_low/count
    avr_max = avr_max/count
    
    avr = format(avr_temp,".2f")
    avr_low = format(avr_low,".2f")
    avr_max = format(avr_max,".2f")
    
    f.close()
    print("*** Anunual Temperature Report for Seoul in 2022 ***")
    print("Average Temperature:",avr,"Celsius")
    print("Average Minimum Temperature:",avr_low,"Celsius")
    print("Average Maximum Temperature:",avr_max,"Celsius")
        
    
if __name__ == "__main__":
    main()

*** Anunual Temperature Report for Seoul in 2022 ***
Average Temperature: 13.30 Celsius
Average Minimum Temperature: 9.18 Celsius
Average Maximum Temperature: 18.08 Celsius

In [125]:
import csv

def main():
    f = open('Seoul_Temp.csv','r',encoding='cp949')
    data = csv.reader(f)
    header = next(data)
    
    day = 0
    maxDay = 0
    lowDay = float("inf")
    low_date = ""
    
    #일교차 = 최고기온-최저기온
    for row in data:
        if(row[-1]==''):
            continue
        if(row[-2]==''):
            continue
        row[-1] = float(row[-1])
        row[-2] = float(row[-2])
        day = row[-1] - row[-2]
        if(maxDay<day):
            max_date = row[0]          
            maxDay = day
        if(lowDay>day):
            low_date = row[0]
            lowDay = day
            
    for a in data:
        if(a[-1]==''):
            continue
        if(a[-2]==''):
            continue
        a[-1] = float(a[-1])
        a[-2] = float(a[-2])
        day = a[-1] - a[-2]
        if(lowDay>day):
            low_date = a[0]
            lowDay = day
    
    
    f.close()
    print(max_date,maxDay)
    print(low_date,format(lowDay,".1f"))
    
    print("*** Anunual Temperature Report for Seoul in 2022 ***")
    print("Day with the Largest Temperature Variation:",max_date)
    print("Maximum Temperature Difference:",maxDay,"Celsius")
    print("Day with the Smallest Temperature Variation:",low_date)
    print("Minimum Temperature Difference:", format(lowDay,".1f"),"Celsius")
    

if __name__ == "__main__":
    main()

2022-11-29 16.6
2022-06-29 1.7
*** Anunual Temperature Report for Seoul in 2022 ***
Day with the Largest Temperature Variation: 2022-11-29
Maximum Temperature Difference: 16.6 Celsius
Day with the Smallest Temperature Variation: 2022-06-29
Minimum Temperature Difference: 1.7 Celsius

In [178]:
import csv

def main():
    f = open('Seoul_Subway.csv','r',encoding='cp949')
    data = csv.reader(f)
    header = next(data)
    sation_max = ['','','','']
    sation_low= ['','','','']

    max_total = [0,0,0,0]
    low_total = [float('inf'),float('inf'),float('inf'),float('inf')]

    for row in data:
        if(row[1]== "1호선"):
            idx = 0
            row[-2] = int(row[-2])
            row[-3] = int(row[-3])
            total = row[-2]+row[-3]
            if(total>max_total[idx]):
                sation_max[idx] = row[3]
                max_total[idx] = total
            if(total<low_total[0]):
                sation_low[idx] = row[3]
                low_total[0] = total
        elif(row[1]=="2호선"):
            idx = 1
            row[-2] = int(row[-2])
            row[-3] = int(row[-3])
            total = row[-2]+row[-3]
            if(total>max_total[idx]):
                sation_max[idx] = row[3]
                max_total[idx] = total
            if(total<low_total[idx]):
                sation_low[idx] = row[3]
                low_total[idx] = total
        elif(row[1]=="3호선"):
            idx = 2
            row[-2] = int(row[-2])
            row[-3] = int(row[-3])
            total = row[-2]+row[-3]
            if(total>max_total[idx]):
                sation_max[idx] = row[3]
                max_total[idx] = total
            if(total<low_total[idx]):
                sation_low[idx] = row[3]
                low_total[idx] = total
        elif(row[1]=="4호선"):
            idx = 3
            row[-2] = int(row[-2])
            row[-3] = int(row[-3])
            total = row[-2]+row[-3]
            if(total>max_total[idx]):
                sation_max[idx] = row[3]
                max_total[idx] = total
            if(total<low_total[idx]):
                sation_low[idx] = row[3]
                low_total[idx] = total
        
        
    
    f.close()

    print("*** Subway Report for Seoul on March 2023 ***")
    for i in range(0,4):
        print("LIne ",i+1,":")
        print("Busiest Station:",sation_max[i], max_total[i])
        print("Least uese Station:",sation_low[i], low_total[i])
        
    
if __name__ == "__main__":
    main()

*** Subway Report for Seoul on March 2023 ***
LIne  1 :
Busiest Station: 서울역 3084227
Least uese Station: 동묘앞 658566
LIne  2 :
Busiest Station: 강남 4690366
Least uese Station: 도림천 80084
LIne  3 :
Busiest Station: 고속터미널 2886887
Least uese Station: 충무로 48
LIne  4 :
Busiest Station: 혜화 2286709
Least uese Station: 남태령 79916